### PR TITLE
refactor: clean up builder creations and paths detection

### PR DESCRIPTION
**Pull request by alan-agius4**
Use workspaceRoot instead of workspace.root. The former uses FS paths while the latter uses Devkit paths. These are not interchangeable.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Sorry, I was very busy and did not have the time to take a closer look. 
Could there be any compatibility problems for the existing builders if we change this part?

**Comment by alan-agius4** [comment]
> Could there be any compatibility problems for the existing builders if we change this part?

No, cause existing builders will not get this code, and if they to apply the changes done in this PR, they will continue to work if they are using Angular CLI 8.0+.

**Comment by alan-agius4** [comment]
Bdw, it seems that circle ci is not running!

**Comment by JohannesHoppe** [comment]
> Bdw, it seems that circle ci is not running!

Oops, I need to reconnect Circle Cl to the repo. Thanks for the hint! 👍 

I will do the merge very soon and will try out the new code on [angular-cli-ghpages](https://github.com/angular-schule/angular-cli-ghpages) first.

**Comment by JohannesHoppe** [comment]
obsolete now

**Pull request closed without merging**
