### PR TITLE
feat: add support for Angular v11

### PR DESCRIPTION
**Pull request by JohannesHoppe**
also adds various backported changes from angular-cli-ghpages.

* feat: add support for Angular v11 (see https://github.com/angular-schule/angular-cli-ghpages/pull/118 and https://github.com/angular-schule/angular-cli-ghpages/pull/120) by @beeman & @johanneshoppe
   * migrate from `configuration` to `buildTarget` (see https://github.com/angular-schule/angular-cli-ghpages/pull/120 for an explanation)
* fix: removes astronaut emoij (since 👨‍🚀 emoij is combined (🧑‍🚀) and breaks on some cmds)
* fix(tooling): fix jest types (https://github.com/angular-schule/angular-cli-ghpages/commit/24d99220c0b443850d8e4ae53c7c99b93da3e53b), as explained in https://github.com/angular-schule/ngx-deploy-starter/issues/7#issuecomment-550575514 by @dianjuar
* fix(tooling): improve prettier formatter (https://github.com/angular-schule/angular-cli-ghpages/pull/120/commits/891ee8c0b438507a532b4aad15ed27804dae6c67), as reported in https://github.com/angular-schule/ngx-deploy-starter/issues/10
* updated docs

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Hello friends! Please update your builders! Your feedback is welcome. 🙂 👍 

* TODO: https://github.com/kauppfbi/ngx-deploy-docker by @kauppfbi
* TODO: https://github.com/bikecoders/ngx-deploy-npm by @yossely and @dianjuar

This is also of interest for @santoshyadavdev ! Please rename `configuration ` (https://github.com/ngx-builders/netlify-builder/blob/3f2517a897360904b12c9a30c5dab3784f8e53a8/src/deploy/schema.d.ts#L2) to `buildTarget` as suggested by @alan-agius4 . I will propose a follow-up [RFC](https://github.com/angular-schule/ngx-deploy-starter/discussions/1) soon.

**Comment by dianjuar** [comment]
Our builder is already up to date

**Comment by JohannesHoppe** [comment]
> Our builder is already [up to date](https://github.com/bikecoders/ngx-deploy-npm/issues/27) with the V11

@dianjuar Excellent! ✅

**Comment by kauppfbi** [comment]
> Hello friends! Please update your builders! Your feedback is welcome. 🙂 👍
> 
> * TODO: https://github.com/kauppfbi/ngx-deploy-docker by @kauppfbi
> * https://github.com/bikecoders/ngx-deploy-npm by @yossely and @dianjuar ✅
> * TODO: https://github.com/vercel/ng-deploy by @huv1k
> 
> This is also of interest for @santoshyadavdev ! Please rename `configuration ` (https://github.com/ngx-builders/netlify-builder/blob/3f2517a897360904b12c9a30c5dab3784f8e53a8/src/deploy/schema.d.ts#L2) to `buildTarget` as suggested by @alan-agius4 . I will propose a follow-up [RFC](https://github.com/angular-schule/ngx-deploy-starter/discussions/1) soon.

Thanks for the reminder and the references 🥇

**Comment by huv1k** [comment]
I am not maintaining `ng-deploy` anymore. 😇🙏 Contact somebody from Vercel.

**Comment by JohannesHoppe** [comment]
@huv1k Thank you very much for this information. I created an issue in the vercel-repo and hope for a reply.

Good luck with your next engagement, too! 🙂 👍

**Pull request merged**
